# Generated by Django 2.0.3 on 2018-11-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('heading', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
